services:
  - type: web
    name: othmane-chaikhi-academie
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: othmane-chaikhi-academie.onrender.com
      - key: DATABASE_ENGINE
        value: django.db.backends.mysql
      - key: DATABASE_NAME
        fromDatabase:
          name: portfolio-mysql
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: portfolio-mysql
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: portfolio-mysql
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: portfolio-mysql
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: portfolio-mysql
          property: port
      - key: CORS_ALLOWED_ORIGINS
        value: https://jade-quokka-a7aef2.netlify.app
      - key: GEMINI_API_KEY
        value: AIzaSyD0j3-ZOf4Jlm_JnT--o6pezzR09Cx-E5A

databases:
  - name: portfolio-mysql
    plan: free
    databaseType: mysql
