# Generated by Django 5.0.1 on 2025-10-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter profile URL', null=True),
        ),
    ]
