# Generated by Django 5.0.1 on 2025-10-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_siteconfig_email_siteconfig_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about_text',
            field=models.TextField(blank=True, help_text='About me section text', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_description',
            field=models.TextField(blank=True, help_text='Description text on home page', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_subtitle',
            field=models.CharField(blank=True, default='Ingénieur en Informatique et Réseaux', help_text='Subtitle on home page', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_title',
            field=models.CharField(blank=True, default='Othmane Chaikhi', help_text='Main title on home page', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='skills_json',
            field=models.JSONField(blank=True, help_text='Skills as JSON array', null=True),
        ),
    ]
